#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude=node_modules --exclude=bower_components --languages=-sql
mv .git/tags.$$ .git/tags
